export const cartActionTypes = {
    TOGGEL_CARD_HIDDEN:'TOGGEL_CARD_HIDDEN',
    ADD_ITEMS : 'ADD_ITEMS',
    CLEAR_ITEM_FROM_STATE :'CLEAR_ITEM_FROM_STATE',
    REMOVE_ITEM: 'REMOVE_ITEM',
    CLEAR_CART:'CLEAR_CART',
    HIDDEN_CART_AT_FIRST: 'HIDDEN_CART_AT_FIRST'
}